### ISSUE TITLE
I got error 'IndexError: list index out of range'

### ISSUE THREAD

**Issue by jhq1234** [cassiePython/NeRF-Art#2]
Hi, thanks for uploading this great code. I really enjoy your work.
I followed your setup introduction and made 'nerfart' environment successfully.
I would like to render the result from pre-trained model with your supported data and weights, but I got this error.

```
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/volsdf_fangzhou_vangogh.pt'
```
From the pretrained weight file, you uploaded, I found that this file is named 'volsdf_fangzhou_van.pt.'
So, I renamed the file name to 'volsdf_fangzhou_vangogh.pt' and I run the rendering code. But I got error message like below.

```
=> Parse extra configs:  []
=> Use cuda devices: [0, 1]
2023-01-05 20:08:12,420-rk0-render.py#265:=> Use ckpt:./pretrained/volsdf_fangzhou_vangogh.pt
Traceback (most recent call last):
  File "render.py", line 647, in <module>
    main_function(config)
  File "render.py", line 286, in main_function
    dataset = get_data(args, downscale=args.downscale)
  File "/home/park/Desktop/NeRF-Art/dataio/__init__.py", line 21, in get_data
    dataset = SceneDataset(**cfgs)
  File "/home/park/Desktop/NeRF-Art/dataio/DTU.py", line 35, in __init__
    tmp_rgb = load_rgb(image_paths[0], downscale)
IndexError: list index out of range
```

Do you know how I can solve this problem?

Thanks.

**Comment by songrise** [comment]
Hello @jhq1234 . First of all, thank you for pointing out my wrong file naming. Regarding your question, It seems that the `image_paths` is an empty list. Did you download the dataset (containing image and camera pose file) and put it under the correct path? If you did not you can first try and see if the issue persists. 

We need the camera pose in testing time (for calculating the center of the scene) but the image is not needed, I will probably remove this when releasing training code.

**Comment by jhq1234** [comment]
Thanks for reply this question @songrise. 
I made a mistake about the dataset path.
This solution works for me.
Thanks!

When does the training code release?

**Comment by songrise** [comment]
> Thanks for reply this question @songrise. I made a mistake about the dataset path. This solution works for me. Thanks!
> 
> When does the training code release?

For training code please refer to issue [#1](https://github.com/cassiePython/NeRF-Art/issues/1)
