### ISSUE TITLE
GPU memory consumption during training

### ISSUE THREAD

**Issue by sosppxo** [cassiePython/NeRF-Art#3]
Thanks for your great job! However, in view of the full-ray sampling strategy you proposed, I am curious and confused about the GPU memory usage during training. Even just generating a full calculation graph, I think it will take up a lot of GPU memory compared with the baseline model. So, may I ask the GPU memory consumption during training?

**Comment by cassiePython** [comment]
@sosppxo It will only take up a little GPU memory. As there are some minutiae to implement this process, I can share a template of the GPU memory-saving technique via email. My email is cwang355-c@my.cityu.edu.hk

**Comment by sosppxo** [comment]
Thank you! I have sent the email by wuchangli@stu.xmu.edu.cn, looking forward to your share ^_^

**Comment by qingyuemeng** [comment]
@cassiePython  I was confused about the problem too, I tried to implemented the training process, but it was always ``` out of memory```.
Can you share me the details about the GPU memory-saving technique, if possible. Thank you very much.

**Comment by songrise** [comment]
> @sosppxo It will only take up a little GPU memory. As there are some minutiae to implement this process, I can share a template of the GPU memory-saving technique via email. My email is [cwang355-c@my.cityu.edu.hk](mailto:cwang355-c@my.cityu.edu.hk)

As a reference, I remember that it takes around 16G GPU memory in our experiment.
