### ISSUE TITLE
Question about perceptual loss

### ISSUE THREAD

**Issue by william2ai** [cassiePython/NeRF-Art#4]
Hi, I'm very interested in your essay, it's really a nice and inviting work. However, it seems there still need some time for you to open-source the overall code, may I ask the detail of how to design the perceptual loss part, since most NeRF randomize rays while training, I don't know how you managed to design the patches used for perceptual loss.  Thanks!

**Comment by cassiePython** [comment]
Thanks for your kind words. The perceptual loss is defined on the whole rendered image. We render all rays while training and use the memory-saving technique to update the gradient. I would like to share the loss functions and the memory-saving technique via email. Please feel free to contact me via email.

**Comment by william2ai** [comment]
@cassiePython Hi, thanks for your reply! I've sent you an email, it's really kind of you to share your amazing idea! Thanks

**Comment by cassiePython** [comment]
@william0620 Please find the attached file in your email. Hope you all the success!

**Comment by jhq1234** [comment]
@cassiePython May I request you about the 'memory-saving technique' when rendering whole image? I want to know about this too! :)
