### ISSUE TITLE
Pretrained checkpoint of girl's dataset

### ISSUE THREAD

**Issue by JinchengLiang** [cassiePython/NeRF-Art#9]
Hi,你好！请问一下有没有dataset中girl的预训练好的模型呢？
谢谢！

**Comment by cassiePython** [comment]
We already provided the pre-trained girl model. For your convenience, you can also download it using this link  https://portland-my.sharepoint.com/:u:/g/personal/cwang355-c_my_cityu_edu_hk/ESlWkpdiu0FOslTGiOulXP4Bn1Au2YWD9dMI41_AP5L3Nw?e=SfvauL
